services:
  postgres:
    image: postgres:15
    container_name: postgres_usuariosapp
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: usuariosapp
      POSTGRES_USER: usuariosuser
      POSTGRES_PASSWORD: usuariospassword
    volumes:
      - postgres_data_usuariosapp:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data_usuariosapp:
